### ISSUE TITLE
Try with codespell instead

### ISSUE THREAD

**Issue by pawamoy** [pawamoy/mkdocs-spellcheck#11]
https://github.com/codespell-project/codespell

Codespell does not check against a dictionary, so niche terms don't trigger false-positives. Could actually alleviate the need for skip/ignore option.

**Comment by Archmonger** [comment]
I think codespell could be used as an option, such as a "strictness" level

For example `strict=low` would use codespell, while `strict=high` would use dictionaries. I personally prefer the dictionary-based implementation.

**Comment by pawamoy** [comment]
I see, thanks for your feedback :)
I do think it would be nice to have multiple spellcheck backends that users can enable/disable at wish.
