### ISSUE TITLE
Option to set log level

### ISSUE THREAD

**Issue by Archmonger** [pawamoy/mkdocs-spellcheck#14]
**Is your feature request related to a problem? Please describe.**
Currently spelling issues are always console warnings.

**Describe the solution you'd like**
I'd like the ability to set them to errors, in order to use `mkdocs-spellcheck` within GitHub Actions workflows.

I basically want `mkdocs build` to fail on spelling errors, but print out all the spelling errors to console before failing.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by pawamoy** [comment]
I believe that's exactly what you get with MkDocs' strict mode: `mkdocs build -s`.

**Comment by Archmonger** [comment]
Yep I must've missed that. Thanks!
