### ISSUE TITLE
bug: Documentation is slightly confusing

### ISSUE THREAD

**Issue by gugulet-hu-spreadai** [pawamoy/mkdocs-spellcheck#24]
What is the install command? What is the exact syntax?

This returns an error: `pip install mkdocs-spellcheck[all]`, same for `pip install mkdocs-spellcheck-all`

The square brackets are confusing.

**Comment by pawamoy** [comment]
Hi @gugulet-hu-spreadai, thanks for reporting this issue.

> This returns an error:

What error :wink:?

> The square brackets are confusing.

This is the syntax for installing extras, see the spec here: https://packaging.python.org/en/latest/specifications/dependency-specifiers/#extras.

---

I suppose you are using a shell that actually interprets the square brackets, so what you can do is escape them by putting the package name and the extras between quotes:

```bash
pip install 'mkdocs-spellcheck[all]'
```

**Comment by gugulet-hu-spreadai** [comment]
Thank you @pawamoy, that was exactly it!
